complaint_groups:
  ABANDONED BIKE:
  - ABANDONED BIKE
  - ABANDONED VEHICLE
  - OEM DISABLED VEHICLE
  ADOPT A BASKET:
  - ADOPT A BASKET
  - LITTER BASKET COMPLAINT
  - LITTER BASKET REQUEST
  - OVERFLOWING LITTER BASKETS
  - OVERFLOWING RECYCLING BASKETS
  - RECYCLING BASKET COMPLAINT
  ADVOCATE OTHER:
  - ADVOCATE OTHER
  - ADVOCATE PERSONAL EXEMPTIONS
  - ADVOCATE PROP REFUNDS CREDITS
  - TAXPAYER ADVOCATE INQUIRY
  AHV INSPECTION UNIT:
  - AHV INSPECTION UNIT
  - SPECIAL PROJECTS INSPECTION TEAM SPIT
  - X RAY MACHINE EQUIPMENT
  AIR QUALITY:
  - AIR QUALITY
  - INDOOR AIR QUALITY
  ANIMAL ABUSE:
  - ANIMAL ABUSE
  ANIMAL FACILITY NO PERMIT:
  - ANIMAL FACILITY NO PERMIT
  - ANIMAL IN A PARK
  - UNSANITARY ANIMAL FACILITY
  - UNSANITARY ANIMAL PVT PROPERTY
  APPLIANCE:
  - APPLIANCE
  - BOILERS
  - COOLING TOWER
  ASBESTOS:
  - ASBESTOS
  - HAZARDOUS MATERIALS
  - RADIOACTIVE MATERIAL
  ATF:
  - ATF
  - FATF
  BEACH POOL SAUNA COMPLAINT:
  - BEACH POOL SAUNA COMPLAINT
  BENCH:
  - BENCH
  BEREAVEMENT SUPPORT GROUP:
  - BEREAVEMENT SUPPORT GROUP
  BEST SITE SAFETY:
  - BEST SITE SAFETY
  - CONSTRUCTION SAFETY ENFORCEMENT
  - SAFETY
  - SCAFFOLD SAFETY
  BIKE RACK:
  - BIKE RACK
  - BIKE RACK CONDITION
  BIKE ROLLER SKATE CHRONIC:
  - BIKE ROLLER SKATE CHRONIC
  BLOCKED DRIVEWAY:
  - BLOCKED DRIVEWAY
  - OBSTRUCTION
  BOROUGH OFFICE:
  - BOROUGH OFFICE
  - BUILDING MARSHALS OFFICE
  - SPECIAL NATURAL AREA DISTRICT SNAD
  BOTTLED WATER:
  - BOTTLED WATER
  - BUILDING DRINKING WATER TANK
  - STANDING WATER
  BRIDGE CONDITION:
  - BRIDGE CONDITION
  - HIGHWAY CONDITION
  BROKEN MUNI METER:
  - BROKEN MUNI METER
  - BROKEN PARKING METER
  BUILDING USE:
  - BUILDING USE
  - CONSTRUCTION
  - GENERAL CONSTRUCTION
  BUS STOP SHELTER COMPLAINT:
  - BUS STOP SHELTER COMPLAINT
  - BUS STOP SHELTER PLACEMENT
  CALORIE LABELING:
  - CALORIE LABELING
  CANNABIS RETAILER:
  - CANNABIS RETAILER
  - PET SHOP
  CASE MANAGEMENT AGENCY COMPLAINT:
  - CASE MANAGEMENT AGENCY COMPLAINT
  - CONSUMER COMPLAINT
  - HOME CARE PROVIDER COMPLAINT
  - LEGAL SERVICES PROVIDER COMPLAINT
  - MASS GATHERING COMPLAINT
  - PUBLIC PAYPHONE COMPLAINT
  - SENIOR CENTER COMPLAINT
  CITY VEHICLE PLACARD COMPLAINT:
  - FOR HIRE VEHICLE COMPLAINT
  - FOR HIRE VEHICLE REPORT
  - STREET SWEEPING COMPLAINT
  COLLECTION TRUCK NOISE:
  - COLLECTION TRUCK NOISE
  COMMERCIAL DISPOSAL COMPLAINT:
  - COMMERCIAL DISPOSAL COMPLAINT
  - INSTITUTION DISPOSAL COMPLAINT
  - RESIDENTIAL DISPOSAL COMPLAINT
  CONSTRUCTION LEAD DUST:
  - CONSTRUCTION LEAD DUST
  - LEAD
  COVID NON ESSENTIAL CONSTRUCTION:
  - COVID NON ESSENTIAL CONSTRUCTION
  CRANES AND DERRICKS:
  - CRANES AND DERRICKS
  CURB CONDITION:
  - CURB CONDITION
  - ROOT SEWER SIDEWALK CONDITION
  - SIDEWALK CONDITION
  DAMAGED TREE:
  - DAMAGED TREE
  - DEAD DYING TREE
  - DEAD TREE
  - ILLEGAL TREE DAMAGE
  - OVERGROWN TREE BRANCHES
  - UPROOTED STUMP
  DAY CARE:
  - DAY CARE
  DEAD ANIMAL:
  - DEAD ANIMAL
  DEP STREET CONDITION:
  - DEP STREET CONDITION
  - STREET CONDITION
  - STREET LIGHT CONDITION
  DEPT OF INVESTIGATIONS:
  - DEPT OF INVESTIGATIONS
  - EXECUTIVE INSPECTIONS
  - INVESTIGATIONS AND DISCIPLINE IAD
  DERELICT BICYCLE:
  - DERELICT BICYCLE
  - DERELICT VEHICLE
  - DERELICT VEHICLES
  DHS ADVANTAGE LANDLORD BROKER:
  - DHS ADVANTAGE LANDLORD BROKER
  - DHS ADVANTAGE TENANT
  - DHS ADVANTAGE THIRD PARTY
  DIRTY CONDITION:
  - DIRTY CONDITION
  - DIRTY CONDITIONS
  - SANITATION CONDITION
  - SANITATION WORKER OR VEHICLE COMPLAINT
  DISCIPLINE AND SUSPENSION:
  - DISCIPLINE AND SUSPENSION
  - PANHANDLING
  DISORDERLY YOUTH:
  - DISORDERLY YOUTH
  - DRIE
  DOF PARKING TAX EXEMPTION:
  - DOF PARKING TAX EXEMPTION
  - DOF PROPERTY CITY REBATE
  DOF PROPERTY OWNER ISSUE:
  - DOF PROPERTY OWNER ISSUE
  - DOF PROPERTY PAYMENT ISSUE
  - DOF PROPERTY PROPERTY VALUE
  - DOF PROPERTY REDUCTION ISSUE
  - DOF PROPERTY REQUEST COPY
  - DOF PROPERTY RPIE ISSUE
  - DOF PROPERTY UPDATE ACCOUNT
  DOOR WINDOW:
  - DOOR WINDOW
  - WINDOW GUARD
  DPR INTERNAL:
  - DPR INTERNAL
  DRINKING:
  - DRUG ACTIVITY
  - SMOKING
  - SMOKING OR VAPING
  DRINKING WATER:
  - DRINKING WATER
  DRUG ACTIVITY:
  - DRINKING
  DUMPSTER COMPLAINT:
  - DUMPSTER COMPLAINT
  - ILLEGAL DUMPING
  E SCOOTER:
  - E SCOOTER
  - SCRIE
  ELDER CARE:
  - ALZHEIMER S CARE
  - ELDER ABUSE
  ELECTRIC:
  - ELECTRIC
  - ELECTRICAL
  ELECTRONICS WASTE:
  - ELECTRONICS WASTE
  - ELECTRONICS WASTE APPOINTMENT
  - INDUSTRIAL WASTE
  ELEVATOR:
  - ELEVATOR
  - FLOORING STAIRS
  EMERGENCY RESPONSE TEAM ERT:
  - EMERGENCY RESPONSE TEAM ERT
  - NON EMERGENCY POLICE MATTER
  ENCAMPMENT:
  - ENCAMPMENT
  - HOMELESS ENCAMPMENT
  - SUMMER CAMP
  EVICTION:
  - EVICTION
  FACADES:
  - FACADES
  - OUTDOOR DINING
  - OUTSIDE BUILDING
  FACE COVERING VIOLATION:
  - FACE COVERING VIOLATION
  FCST:
  - FCST
  - NONCONST
  FOOD ESTABLISHMENT:
  - FOOD ESTABLISHMENT
  - MOBILE FOOD VENDOR
  - VENDING
  FOOD POISONING:
  - FOOD POISONING
  FORENSIC ENGINEERING:
  - FORENSIC ENGINEERING
  FOUND PROPERTY:
  - FOUND PROPERTY
  - LOST PROPERTY
  GENERAL:
  - GENERAL
  GENERAL CONSTRUCTION PLUMBING:
  - GENERAL CONSTRUCTION PLUMBING
  - PLUMBING
  GRAFFITI:
  - GRAFFITI
  - TATTOOING
  GREEN TAXI COMPLAINT:
  - GREEN TAXI COMPLAINT
  - GREEN TAXI REPORT
  - TAXI COMPLAINT
  - TAXI COMPLIMENT
  - TAXI REPORT
  HARBORING BEES WASPS:
  - HARBORING BEES WASPS
  HEALTH:
  - HEALTH
  - QUALITY OF LIFE
  HEAP ASSISTANCE:
  - HEAP ASSISTANCE
  - UTILITY PROGRAM
  HEAT HOT WATER:
  - HEAT HOT WATER
  - HEATING
  - NON RESIDENTIAL HEAT
  HIGHWAY SIGN DAMAGED:
  - HIGHWAY SIGN DAMAGED
  - HIGHWAY SIGN DANGLING
  - HIGHWAY SIGN MISSING
  - STREET SIGN DAMAGED
  - STREET SIGN DANGLING
  - STREET SIGN MISSING
  HOME DELIVERED MEAL COMPLAINT:
  - HOME DELIVERED MEAL COMPLAINT
  - HOME DELIVERED MEAL MISSED DELIVERY
  HOME REPAIR:
  - HOME REPAIR
  - MAINTENANCE OR FACILITY
  - SCHOOL MAINTENANCE
  HOMELESS PERSON ASSISTANCE:
  - HOMELESS PERSON ASSISTANCE
  - HOMELESS STREET CONDITION
  HOUSING LOW INCOME SENIOR:
  - HOUSING LOW INCOME SENIOR
  - HOUSING OPTIONS
  ILLEGAL ANIMAL KEPT AS PET:
  - ILLEGAL ANIMAL KEPT AS PET
  - ILLEGAL ANIMAL SOLD
  ILLEGAL FIREWORKS:
  - ILLEGAL FIREWORKS
  ILLEGAL PARKING:
  - ILLEGAL PARKING
  - TRAFFIC ILLEGAL PARKING
  ILLEGAL POSTING:
  - ILLEGAL POSTING
  - POSTING ADVERTISEMENT
  INCORRECT DATA:
  - INCORRECT DATA
  INDOOR SEWAGE:
  - INDOOR SEWAGE
  - SEWER
  - SEWER MAINTENANCE
  IOLATION OF PARK RULES:
  - VIOLATION OF PARK RULES
  LIFEGUARD:
  - LIFEGUARD
  LINKNYC:
  - LINKNYC
  LITERATURE REQUEST:
  - LITERATURE REQUEST
  LOT CONDITION:
  - LOT CONDITION
  - VACANT LOT
  MISCELLANEOUS CATEGORIES:
  - MISCELLANEOUS CATEGORIES
  MISSED COLLECTION:
  - MISSED COLLECTION
  - MISSED COLLECTION ALL MATERIALS
  MOLD:
  - MOLD
  MOSQUITOES:
  - MOSQUITOES
  MUNICIPAL PARKING FACILITY:
  - MUNICIPAL PARKING FACILITY
  NEW TREE REQUEST:
  - NEW TREE REQUEST
  - REQUEST XMAS TREE COLLECTION
  NOISE:
  - CITY VEHICLE PLACARD COMPLAINT
  - NOISE
  - NOISE COMMERCIAL
  - NOISE HELICOPTER
  - NOISE HOUSE OF WORSHIP
  - NOISE PARK
  - NOISE RESIDENTIAL
  - NOISE STREET SIDEWALK
  - NOISE SURVEY
  - NOISE VEHICLE
  NONCOMPLIANCE WITH PHASED REOPENING:
  - NONCOMPLIANCE WITH PHASED REOPENING
  - PRIVATE OR CHARTER SCHOOL REOPENING
  OTHER ENFORCEMENT:
  - OTHER ENFORCEMENT
  - REAL TIME ENFORCEMENT
  - VENDOR ENFORCEMENT
  PAINT PLASTER:
  - PAINT PLASTER
  PLANT:
  - PLANT
  - POISON IVY
  PRIVATE SCHOOL VACCINE MANDATE NON COMPLIANCE:
  - PRIVATE SCHOOL VACCINE MANDATE NON COMPLIANCE
  - VACCINE MANDATE NON COMPLIANCE
  PUBLIC TOILET:
  - PUBLIC TOILET
  RECYCLING ENFORCEMENT:
  - RECYCLING ENFORCEMENT
  - SUSTAINABILITY ENFORCEMENT
  REGISTRATION AND TRANSFERS:
  - REGISTRATION AND TRANSFERS
  REQUEST LARGE BULKY ITEM COLLECTION:
  - REQUEST LARGE BULKY ITEM COLLECTION
  - SEASONAL COLLECTION
  RODENT:
  - RODENT
  SNOW:
  - SNOW
  - SNOW OR ICE
  - SNOW REMOVAL
  SPECIAL OPERATIONS:
  - SPECIAL OPERATIONS
  SQUEEGEE:
  - SQUEEGEE
  STALLED SITES:
  - STALLED SITES
  - WOOD PILE REMAINING
  STORM:
  - STORM
  - WEATHERIZATION
  SWEEPING INADEQUATE:
  - SWEEPING INADEQUATE
  - SWEEPING MISSED
  - SWEEPING MISSED INADEQUATE
  TEACHING LEARNING INSTRUCTION:
  - TEACHING LEARNING INSTRUCTION
  TRAFFIC:
  - TRAFFIC
  - TRAFFIC SIGNAL CONDITION
  UNLEASHED DOG:
  - UNLEASHED DOG
  UNSANITARY CONDITION:
  - UNSANITARY CONDITION
  - UNSANITARY PIGEON CONDITION
  URINATING IN PUBLIC:
  - URINATING IN PUBLIC
  WATER CONSERVATION:
  - WATER CONSERVATION
  WATER MAINTENANCE:
  - WATER LEAK
  - WATER MAINTENANCE
  - WATER QUALITY
  - WATER SYSTEM
